package com.alexeyermolovich.secretofyourname.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.alexeyermolovich.secretofyourname.model.NameObjectDao;

import com.alexeyermolovich.secretofyourname.model.NameObjectDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nameObjectDaoDaoConfig;

    private final NameObjectDaoDao nameObjectDaoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nameObjectDaoDaoConfig = daoConfigMap.get(NameObjectDaoDao.class).clone();
        nameObjectDaoDaoConfig.initIdentityScope(type);

        nameObjectDaoDao = new NameObjectDaoDao(nameObjectDaoDaoConfig, this);

        registerDao(NameObjectDao.class, nameObjectDaoDao);
    }
    
    public void clear() {
        nameObjectDaoDaoConfig.getIdentityScope().clear();
    }

    public NameObjectDaoDao getNameObjectDaoDao() {
        return nameObjectDaoDao;
    }

}
