package com.alexeyermolovich.secretofyourname.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NAME_OBJECT_DAO".
 */
public class NameObjectDao {

    private String name;
    private Byte sex;

    public NameObjectDao() {
    }

    public NameObjectDao(String name) {
        this.name = name;
    }

    public NameObjectDao(String name, Byte sex) {
        this.name = name;
        this.sex = sex;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getSex() {
        return sex;
    }

    public void setSex(Byte sex) {
        this.sex = sex;
    }

}
